### ISSUE TITLE
Allow for n-to-1 relationship

### ISSUE THREAD

**Issue by NickGreen** [Prospress/woocommerce-subscriptions-restrict-product#2]
This is coming from a request to have a 4-to-1 relationship between subs and product. To work this into the plugin, there would need to be an entry in the cache for each time a subscription was added, so this line would need to be removed: https://github.com/Prospress/woocommerce-subscriptions-one-to-one/blob/master/wcs-one-to-one.php#L93

Also, instead of checking if the value is in the cache, we'd need to check for a specific number of times it's in there, here: https://github.com/Prospress/woocommerce-subscriptions-one-to-one/blob/master/wcs-one-to-one.php#L122

**Comment by thenbrent** [comment]
With this in mind, I think the plugin name and purpose can be expanded to the more generic to _Use Stock Qty Only for Initial Product Purchase_. That will facilitate both the one-to-one method (by setting Stock Qty to 1), the 4-to-1, and any other combination. It's certainly something I've seen requested previously (it's in a similar vein to [this plugin](https://github.com/Prospress/woocommerce-subscriptions-do-not-reduce-stock-on-renewal), only it goes the extra step of handling when subscriptions are cancelled).

> so this line would need to be removed

You might instead just want to change the cache to:

1. use the `$product_id` as the key in the `$cache` array
1. increment/decrement the value of that based on the activation/deactivation of subscriptions

**Comment by jrick1229** [comment]
Here is the related ticket: https://secure.helpscout.net/conversation/500664389/3874/

**Comment by NickGreen** [comment]
@thenbrent This plugin is actually designed to get around the inventory system completely. To use it effectively, the inventory should be turned off for subscription products. This is important because for the inventory system to prevent a product from being purchased, it also prevents it from being purchased when a failed order is manually paid for.

With this, we will be able to hide products from the front end without preventing them from being purchased when a 'pay now' link is clicked by customers.

Therefore, the name might be better something like _Limit Subscriptions per Product_.

**Comment by thenbrent** [comment]
Ah right of course, I forgot about that. In that case, I wonder if this _Issue_/feature is better served as part of: https://github.com/Prospress/woocommerce-subscriptions-do-not-reduce-stock-on-renewal ?

**Comment by thenbrent** [comment]
> Therefore, the name might be better something like Limit Subscriptions per Product.

The issue with that is the overlap and ambiguity between the use of the term _Limit_ with the [Limit feature](https://docs.woocommerce.com/document/subscriptions/store-manager-guide/#limit-subscription) in Subscriptions. But something like "Restrict product to one" or similar might be suitable.

**Comment by NickGreen** [comment]
Checks for number specified in UI now. Added in https://github.com/Prospress/woocommerce-subscriptions-restrict-product/commit/546c1ea56e66494dd26aa3eafb3d3e3d00e5a49f
