### ISSUE TITLE
Not restricting at all.  

### ISSUE THREAD

**Issue by MrPigeonweb** [Prospress/woocommerce-subscriptions-restrict-product#9]
Hi there. 

I have installed it and set the limit to 6 on a product with 6 active subscriptions and it is not doing anything. 

Basically you can still add the product to the cart. and If I change the quantity available to 0 or make the product Out of stock renewals do not work as they can not be added to the cart if the product is out of stock. 

I have read the note about not restricting retroactively. Does this mean if I have 8 active subscriptions before I install the plugin it wont start restricting until 8 more are booked? 

Thanks

**Comment by NickGreen** [comment]
Hello, we also have an open ticket for you, so we will deal with it there. Just a couple of notes, in case anyone stumbles across this publicly:

> I have installed it and set the limit to 6 on a product with 6 active subscriptions and it is not doing anything.

> I have read the note about not restricting retroactively. Does this mean if I have 8 active subscriptions before I install the plugin it wont start restricting until 8 more are booked?

This is not expected. When the plugin is installed, it should make a list of all unended subscriptions for a product and act on that number.

The "retroactive" note just means that if you already have more than 8 booked when you activate the plugin, it won't cancel any pre-existing subscriptions, it will only prevent future purchases.

I will follow up with you in the ticket for your specific situation, and we will get it fixed up! Thanks.

**Comment by NickGreen** [comment]
This has been fixed with  e70ad36
